management:
  endpoints:
    web:
      exposure:
        include: info,prometheus,threaddump,heapdump,env,beans
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: webflux-sandbox
  thymeleaf:
    reactive:
      max-chunk-size: 1024
